[package]
name = "kodama-dsp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
wee_alloc = "0.4"

[build-dependencies]
cbindgen = "0.26"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
codegen-units = 1
